---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: microk8s-sandbox-git
  namespace: tekton-pipelines
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/mikepatterson/microk8s-sandbox.git

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: microk8s-sandbox-image
  namespace: tekton-pipelines
spec:
  type: image
  params:
    - name: url
      value: # image registry (.e.g. 10.0.0.131:5050/microk8s-sandbox)
